# SPDX-License-Identifier: EUPL-1.2
# SOPS-regels voor de kooi-secrets. Versleutel ALLEEN de waarden (data/stringData)
# zodat de YAML-structuur diffbaar blijft in git. De age-recipient hieronder is de
# PUBLIEKE cluster-age-key; de bijbehorende PRIVÉ-key staat alleen op de
# orchestrator-host (= kroonjuweel) en verlaat die nooit.
creation_rules:
  - path_regex: cage/secrets/.*\.enc\.yaml$
    encrypted_regex: "^(data|stringData)$"
    # Cluster-age publieke key (bootstrap 2026-07-18). De privé-key staat in
    # ~/.config/sops/age/habitat.txt op de orchestrator-host (nu: ubuntu@cp-01).
    age: "age19722z4grmykmt9dmngmgu3r7s7xqgdal3k8dm2r2atq53kq5u5rq4m9mvq"
