apiVersion: v1
kind: Secret
metadata:
    name: pat-node-01
    namespace: agents
    labels:
        habitat/node: "01"
type: Opaque
data:
    GIT_PAT: ENC[AES256_GCM,data:RkBh2QZ8Md4zyI0fcGxTX7qqXNy5otgwsaafEjT0zy017JaLOrdqQxf+HGADvlU/D+uOrhcPtgA=,iv:itZJGYADCoGJf/KKLK/7sM9JpVLo2jWkMjq1gWxVytA=,tag:U8o105yrJMjln5Sx1iQ/tg==,type:str]
sops:
    age:
        - recipient: age19722z4grmykmt9dmngmgu3r7s7xqgdal3k8dm2r2atq53kq5u5rq4m9mvq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBMklkQlR4bVZRV3VaS1VV
            Zk1WUklrajB5Y3JrNHNmb21WbzJhNWZoZkdJCnNVdUxuMWZma0YrNzFDV0VJQ3Qv
            akdhSW01NnpzdDNuWmk1VTJ3em5PeDQKLS0tIHczVDBoNlZXRDVwNERmSm9YUWtD
            SXp1bWxXaDJIRmtGaGVrWEhCZTlyemsKtkPARVrYFgYpD4RxeJ/66V+vGiUUVXIG
            HZlgCaKlZ13QlE8Q6IoSD0cL5neT7Rn0iLtP3GisEPRDtae1ZKF1nA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-18T18:49:13Z"
    mac: ENC[AES256_GCM,data:ViakB+91VJ1flMtHUab+POpXqHvL+OqJVraKfgfU+SN9jnbZd0e629nX26a10HBQdlog9gQsMtMUnYBl2nahqFwdK1n6k3yZ/aCQSRpVn930TuEfm8CENbmOS2vPceJv4wv9eH7Ta8LSQr48ERtnki17p2QD3CWcWIIcWj12rNk=,iv:N6ytcFfcTQcIt0gJ4SQmO9p99KkmE6ky9wcaCvqlqoU=,tag:vo2SO/1vqa6HERarQcfsXQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
