# SPDX-License-Identifier: EUPL-1.2
# TEMPLATE — één per node (pat-node-01, pat-node-02, ...). Single-repo fine-grained
# PAT met contents:write. Kopieer naar pat-node-<n>.enc.yaml, vul de waarde, en
# versleutel met `sops -e -i` (zie README.md). Commit nooit plaintext.
apiVersion: v1
kind: Secret
metadata:
  name: pat-node-01
  namespace: agents
  labels:
    habitat/node: "01"
type: Opaque
stringData:
  GIT_PAT: "github_pat_PLACEHOLDER"
